framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Namespaced pools use the above "app" backend by default
        pools:
            respondent.session.cache:
                # TODO только на linux
                # adapter: cache.adapter.redis
                # default_redis_provider: redis://localhost

                adapter: cache.adapter.doctrine_dbal
                default_lifetime: 86400  # One day
